### ISSUE TITLE
The core config class has been moved - cannot import name 'Config' from 'homeassistant.core' (/usr/src/homeassistant/homeassistant/core.py). Did you mean: 'config'?

### ISSUE THREAD

**Issue by jorisrymenants** [DennisB66/HA-Buienradar-Precipitation-Forecast#22]
This custom component has stopped working in HA version 2026.1.1. Maybe already 2026.1.0 but I skipped that version.

reason is this change:
https://developers.home-assistant.io/blog/2024/10/31/core-config-moved/

The existing \_\_init\_\_.py is already partially correct. It no longer uses this Config, but Config is still imported, so error occurs and component does not load.

Please change your \_\_init\_\_.py and remove the import of Config:

from homeassistant.const import CONF_LATITUDE, CONF_LONGITUDE
from homeassistant.config_entries import ConfigEntry
from homeassistant.core import HomeAssistant             __#, Config__
from homeassistant.helpers.aiohttp_client import async_get_clientsession
